WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fc30748e290>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/openai-whisper/
slurmstepd: error: *** JOB 19909678 ON midway3-0277 CANCELLED AT 2024-04-25T11:25:22 ***
